// 記事は"/static/posts"ディレクトリに置く

= Amazing engineで3年間お世話になったあれこれ
// タイトル
佐藤 公平 <kouhei.hamu@gmail.com>
// 姓 名 <メールアドレス(省略可)> 
v1.0, 2012-03-01 00:00
//ヴァージョン(省略可), 日時("YYYY-MM-DD HH:MM"の形式で記述)
:page-category: 社内
// カテゴリー([プログラミング、インフラ、ゲーム、社内、その他]から選択)
:page-thumbnail: /images/kohei/intern-last/kubernetes.png
// サムネイル("/images/(ファイル名)"の形式で記述)
// 画像は"/static/images"に置く


// ここから本文
== <はじめに> +

初めまして！ auと申します。 +

Amazing engine株式会社にインターン生として大学1年生の春休みの2月から迎え入れていただき、今年の4月から社会人になるまでの約3年間お世話になりました。 +

おかげさまで将来やりたいことも見つかり、ソフトウェア開発エンジニアとして内定を獲得できました。 +

ここでエンジニアとして鍛えて貰えなければ今の自分はないと思いますし、もしかしたらエンジニア以外の意味に進んでいたかもしれません。 +

それくらい多くのことを学ばせていただきました。 +

面接の時は…という風に書いていると恐ろしく長くなってしまうと思うので、こちらでインターンをすることになった経緯、実績、そして現在どんなエンジニアになれたのかを書いていこうと思います。 +

== インターンをすることになったきっかけ +

私は情報系大学に通っており、成績もプログラミングに関する知識も周りと比べても良くも悪くもなく、特にできているということではありませんでした。 +

将来ゲームとか作ってみたいなーとか思っていましたが、本当にこのままでなれるのかな？と思って、自分から何かそれっぽいことをしてみようと思ったことがきっかけです。 +

前述した通り、技術力はないし何ならポートフォリオなんてものもありませんでした。今思えばインターンに参加する前に何か作っておけばいいのかなと思いますし、はたまたとりあえず行動したことを褒めるべきなのかなとも思います。 +

そんな中、こんな私をエンジニアとして迎え入れてくれて、1年間は勉強をしてその後に開発とかをしてくれればいいと言ってくれました。 +

実際に会社に貢献できたと感じることは少ないのが申し訳ないです。 +

そんなことがあり、毎日技術ブログを書いたり、学校で学ばない読みやすいコーディングのルールを教えて貰ったりと、たくさんの時間を割いて貰いました。 +

そんな中でもこれが実績だ！と言えるものがこちらです！ +

== 実績

一覧 +
*技術ブログ +
*初めてのゲーム開発: DotGoal +
*音声文字起こしアプリ: natadecoco +
*ビデオ通話をしながら何かをしよう！: snack-meet +
*Discordに潤いをもたらすシステム: moisturer +

=== 技術ブログ

インターン生としての初めての仕事が「毎日勉強したことや分からなかったことをブログにまとめる」ということでした。 +

今でも書いている技術ブログである「auの日記」がこちらです。 +
https://program-shoshinsya.hatenablog.com/ +

2021年3月でのPVは410,000となっており、日々伸びています。ありがとうございます。 +

今まで書いてきた記事の中でもバズった記事を2つ紹介します。

1. Unreal Engine4の本を半分読んだ初心者が100時間でゲームを完成させてみた

こちらはUnreal Engine4を使ってゲームを作成した際の記事です。 +

はてブ砲を受けてバズり、ブックマーク250を超えて週間ランキングにも載ることができた記事です。 +

今思えば論文くらいの分量があるので章ごとに記事にするべきかなとも思いましたが、数日で何万PVときたのは本当に嬉しかったことを覚えています。 +

詳細な内容は記事に全て書いてあります。

記事へのリンク: https://program-shoshinsya.hatenablog.com/entry/2019/03/21/171000

2. スプラトゥーン全国大会優勝経験者に教わりながらスプラトゥーン2の勝てるプレイングを教えてもらった

2つ目の記事はゲームに関する記事です。 +

同じインターンの先輩がスプラトゥーンの大会に出て活躍しており、しかも何故勝てるのかを言語化できる人でした。 +

今でも交流があり、たまに連絡を取ったり食事をしたりしています。 +

スプラトゥーンは4VS4のチームで戦うゲームなので、ルールによって戦術が異なっていて面白いゲームです。 +

元々こう言った銃で打ち合ったりPvP(Player VS Player)が苦手でしたが、今では友達とやっているくらい好きになりました。 +

どうすれば勝てるかを考えてそれがぶっ刺さった時は本当に楽しいよね。 +

そんな楽しさや奥深さを教えてくれた先輩とやっていたYouTubeチャンネルがこちらです。 +

YouTubeへのリンク: https://www.youtube.com/channel/UChuzPpSc71j9HLYF0-57cmA

記事へのリンク: https://program-shoshinsya.hatenablog.com/entry/2018/11/19/161145

=== 初めてのゲーム開発: DotGoal

実績の2つ目はブログの最初にも書いたゲーム開発です。 +

元々はゲームプログラマーになりたかったので、話し合いをしてゲームを作ることにしました。 +

実際にできたゲームがこちらです。 +
<iframe width="589" height="368" src="https://www.youtube.com/embed/Vo8OKn_cKwU" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Unreal Engine4を用いて、全てブループリントを使って開発しました。

ゲームの動作1つ1つは本当に手で作られており、それをサポートするゲームエンジンでさえUIが複雑で覚えることがたくさんありました。 +

このゲームは全てブループリントで作られているためバグはほとんどないですが、C++で書いていたらこの時の技術力だと死んでいたかもしれないです。 +

=== 音声文字起こしアプリ: natadecoco

実績の3つ目は音声を文字起こしして繋ぎ合わせることができる「natadecoco」というアプリです。 +

初めて？社長からこんなアプリのアイデアがあるからアプリにしてくれと言われてSwiftを使って作成しました。 +

Speech-to-TextというAPIを使い、音声を認識して候補として出てくる文字をつなげることでメモができるアプリです。 +

=== ビデオ通話をしながら何かをしよう！: snack-meet

実績の4つ目はビデオ通話をしながら自由に機能を拡張できる「snack-meet」というアプリです。

コロナウイルスの影響で身篭り需要が高まっていたことから、ビデオ通話アプリが活躍していましたが、ビデオの画面を常に出しながら作業ができれば面白いのではないかということから作りました。

これはVue.jsで作成されており、ビデオ通話をしている画面の周りに機能を拡張できる「パネル」があります。

あとはエンジニア次第で自由に扱いやすくカスタマイズ！

GitHubで公開していることと、開発についてまとめた記事が以下の通りです。

GitHub: https://github.com/au-niji/snack-meet
ブログの記事: https://program-shoshinsya.hatenablog.com/entry/2020/07/01/221000

=== Discordに潤いをもたらすシステム: moisturer

実績の5つ目は社長のDiscordが寂しいという要望から生まれたmoistureというアプリです。 +

PythonでWebサイトのスクレイピングを行い、対象のDiscordに整形した形で送信します。 +

どんな情報があってどんな形式なら送信できるのか、Redisにどんなキーなら早くできそうかということを考えて楽しかったことを覚えています。ヒントをいっぱいもらいましたが・・・。 +

=== 

// 画像は"/static/images"に置く

// その他はAsciidoc準拠
